config/routes.rb
Rails.application.routes.draw do

  root   'basic_pages#home'
  get    '/about',                to: 'basic_pages#about'
  get    '/addin-support',        to: 'basic_pages#addin_support'
  get    '/privacy',              to: 'basic_pages#privacy'
  get    '/pricing',              to: 'basic_pages#pricing'
  get    '/purchase-complete',    to: 'basic_pages#purchase_complete'
  get    '/join-tips',            to: 'basic_pages#join_tips'
  get    '/libraries',            to: 'basic_pages#libraries'
  get    '/community-centers',    to: 'basic_pages#community_centers'
  get    '/training',             to: 'basic_pages#training'
  get    '/excel-training/:slug', to: 'basic_pages#cities', as: 'city', constraints: CityConstraint.new

  resources :tips, path: "spreadsheet-tips", param: :slug, only: [:index, :show]
  get '/tips', to: redirect('/spreadsheet-tips')
  get '/tips/:tip_name', to: redirect('/spreadsheet-tips/%{tip_name}')

  resources :charges, only: [:create]

  # Devise routes for the main website.
  devise_for :users,
    controllers: {
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
  # Additional routes for custom actions
  devise_scope :user do
    put 'users/update_password', to: 'users/registrations#update_password'
    put 'users/update_info', to: 'users/registrations#update_info'
  end
  # Short url with redirect created for giveaway cards and other printed materials.
  get '/sign-up', to: redirect('/users/sign_up')

  # Redirects from version 1 of the product (since there are still some old links out there)
  get '/courses(/*all)', to: redirect(path: '/#courses')

  # Routes namespaced under /addin
  namespace :addin do
    root 'basic_pages#index', as: :root
    get  'purchase-complete', to: 'basic_pages#purchase_complete'

    resources :charges, only: [:create]

    # Creates
    #  /addin/courses
    resources :courses, only: [:index, :show] do

      # Creates
      #   /addin/courses/:id/conclusion
      get 'conclusion', on: :member

      # Creates
      #  /addin/courses/:id/lessons
      #  /addin/courses/:id/lessons/:number_in_course
      resources :lessons, param: :number_in_course, only: [:index, :show] do

        # Creates
        #   /addin/courses/:id/lessons/:number_in_course/challenge
        #   /addin/courses/:id/lessons/:number_in_course/full-screen-video
        get 'challenge', on: :member
        get 'fullscreen', on: :member
      end
    end

    post 'feedback/create', to: 'feedback#create'
    post 'feedback/create-challenge', to: 'feedback#createChallenge'
    post 'completions/create', to: 'completions#create'

    # Devise routes & controllers for the addin.
    #
    # The main website and addin have their own devise routes and controllers but they share the model.
    #
    # See the routes "devise_for" generates at:
    #   http://www.rubydoc.info/github/plataformatec/devise/master/ActionDispatch/Routing/Mapper%3Adevise_for
    devise_for :users, skip: [:passwords, :confirmations], skip_helpers: true,
      controllers: {
        registrations: 'addin/users/registrations',
        sessions: 'addin/users/sessions'
      },
      path_names: {
        sign_in: 'login',
        sign_out: 'logout'
      }
    # Additional routes for custom actions
    devise_scope :addin_user do
      put 'users/update_password', to: 'users/registrations#update_password'
      put 'users/update_info', to: 'users/registrations#update_info'
      get 'users/password/new', to: 'users/passwords#new'
      get 'users/confirmation/new', to: 'users/confirmations#new'
    end
    # Redirects for people using the addin's "up one level" button.
    get 'users', to: redirect('/addin/courses', status: 302)
    get 'users/password', to: redirect('/addin/users/login', status: 302)
    get 'users/confirmation', to: redirect('/addin/users/login', status: 302)
  end

  namespace :admin do
    root to: "courses#index"
    resources :courses
    resources :lessons
    resources :users
    resources :tips
    resources :course_completions
    resources :lesson_completions
    resources :challenge_completions
    resources :whitelisted_ips
  end
end
# (For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html)

app/views/shared/_devise-links.html.erb
<div class="devise-links">
  <%- if controller_name != 'sessions' %>
    <div class="devise-link">Already have an account? <%= link_to "Log in", new_session_path(resource_name) %></div>
  <% end -%>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <div class="devise-link">Don't have an account? <%= link_to "Sign up for free", new_registration_path(resource_name) %></div>
  <% end -%>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <div class="devise-link"><%= link_to "Forgot your password?", new_password_path(resource_name) %></div>
  <% end -%>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <div class="devise-link"><%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %></div>
  <% end -%>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <div class="devise-link"><%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %></div>
  <% end -%>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <div class="devise-link"><%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %></div>
    <% end -%>
  <% end -%>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="message-box <%= message_type %>"><%= message.html_safe %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="site-footer">
  <div class="site-footer__blocks">
    <div class="site-footer__block">
      <h3>Learn</h3>
      <ul>
        <li><%= link_to "Courses", root_path(:anchor => "courses") %></li>
        <li><%= link_to "Excel Addin", "https://appsource.microsoft.com/en-us/product/office/WA104381078" %></li>
        <li><%= link_to "Spreadsheet Tips", tips_path %></li>
        <li><%= link_to "CustomFormats.com", "https://customformats.com" %></li>
      </ul>
    </div>
    <div class="site-footer__block">
      <h3>Plans</h3>
      <ul>
        <li><%= link_to "Pricing", pricing_path %></li>
        <li><%= link_to "For Libraries", libraries_path %></li>
        <li><%= link_to "For Community Centers", community_centers_path %></li>
        <li><%#= link_to "For Businesses", businesses_path %></li>
      </ul>
    </div>
    <div class="site-footer__block">
      <h3>Company</h3>
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", "mailto:info@gridmaster.io" %></li>
        <li><%= link_to "Privacy Policy", privacy_path %></li>
      </ul>
    </div>
    <div class="site-footer__block">
      <h3>Social</h3>
      <ul>
        <li><%= link_to "Twitter", "https://twitter.com/gridmasterhq" %></li>
        <li><%= link_to "Blog", "https://medium.com/gridmaster" %></li>
      </ul>
    </div>
    <div class="site-footer__block copyright-block">
      <ul>
        <%= link_to "", root_path, class: "site-footer__logo" %>
        <li class="made-with">Made with <span class="made-with-emoji">❤️</span> in Dayton, Ohio</li>
        <li><small>© Copyright <%= Time.current.year %></small></li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_google-analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-65103721-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-65103721-1');
  gtag('config', 'AW-845827519');
</script>

app/views/shared/_header.html.erb
<header class="site-header">
  <div class="page-width">
    <%= link_to "", root_path, class: "home-link" %>
    <nav class="main-nav">
      <%= link_to "Tips", tips_path %>
      <%= link_to "Pricing", pricing_path %>
      <%= link_to "About", about_path %>

      <% if user_signed_in? %>
        <%= link_to "Profile", edit_user_registration_path %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path %>
        <%= link_to "Log In", new_user_session_path %>
      <% end %>
    </nav>
  </div>
</header>

app/views/shared/_promo-video-modal.html.erb
<div class="modal micromodal-slide" id="promo-video" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="promo-video-title">
      <button class="modal__close modal__close--absolute" aria-label="Close modal" data-micromodal-close></button>
      <main id="promo-video-content" class="promo-video__wrapper">
        <iframe
          src="https://player.vimeo.com/video/297375903"
          id="promo-video-iframe"
          class="promo-video__player"
          width="640"
          height="400"
          frameborder="0"
          allowfullscreen>
        </iframe>
      </main>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var promoVideoIframe = document.querySelector('#promo-video-iframe');
    var promoVideoPlayer = new Vimeo.Player(promoVideoIframe);

    MicroModal.init({
      onShow: function() { promoVideoPlayer.play() },
      onClose: function() { promoVideoPlayer.pause() }
    });
  });
</script>

app/views/shared/_simple-header.html.erb
<header class="site-header">
  <div class="page-width">
    <%= link_to "", root_path, class: "home-link" %>
    <nav class="main-nav">
      <%= link_to "About", about_path %>
    </nav>
  </div>
</header>

app/views/shared/_stripe-checkout.html.erb
<%#
  Adds Stripe Checkout (custom) to a page.

  It works by turning any button with a class of .stripe-checkout--premium
  into a premium stripe checkout button.

  This assumes it's only being embedded on a page once, and it's being embedded on
  a page that could have access to current_user (though it's protected in a condition)
%>

<script src="https://checkout.stripe.com/checkout.js"></script>
<script>
  // Global Stripe initialization
  var stripeHandler = StripeCheckout.configure({
    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
    name: 'Gridmaster',
    image: '<%= image_path('gridmaster-128.png') %>',
    email: '<%= current_user.email if current_user %>',
    zipCode: true,
    locale: 'auto',
    allowRememberMe: false,
    token: function(token) {
      GM.hardPost('<%= charges_path %>', {
        authenticity_token: '<%= form_authenticity_token %>',
        stripeEmail: token.email,
        stripeToken: token.id
      });
    }
  });

  // "Premium" Button Setup
  (function() {
    function stripePremiumButtonCallback(e) {
      stripeHandler.open({
        description: 'Premium',
        amount: 7900,
        panelLabel: <% if current_user %>'Upgrade Account'<% else %>'Create Account'<% end %>
      });
      e.preventDefault();
    }

    var stripeButtons = document.querySelectorAll('.stripe-checkout--premium');

    for (i = 0; i < stripeButtons.length; i++) {
      stripeButtons[i].addEventListener('click', stripePremiumButtonCallback);
    }

    // Close Checkout on page navigation:
    window.addEventListener('popstate', function() {
      stripeHandler.close();
    });
  })();
</script>

app/views/shared/_tips-signup-modal.html.erb
<div class="modal micromodal-slide" id="tips-signup-modal" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="promo-video-title">
      <button class="modal__close modal__close--absolute" aria-label="Close modal" data-micromodal-close></button>
      <main>

        <h2 class="tips-signup-title">Get an animated gif Excel tip like this in your inbox each week.</h2>
        <div id="mc_embed_signup" class="tips-modal-signup-wrapper">
          <form action="//gridmaster.us11.list-manage.com/subscribe/post?u=c6aa5d99b8059f1aba3005443&amp;id=cf722f27b0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll" class="email-layout">
              <div class="email-input-wrap">
                <label for="mce-EMAIL" class="email-label">Email Address</label>
                <input type="email" value="" placeholder="example@gmail.com" name="EMAIL" class="required email" id="mce-EMAIL">
              </div>
              <div class="email-submit-wrap">
                <input type="submit" value="Submit" name="subscribe" id="mc-embedded-subscribe" class="email-button" onclick="gtag('event', 'TipsSubscribe', {'event_category': 'Individual Tip Page'});">
              </div>
            </div>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;">
              <input type="text" name="b_c6aa5d99b8059f1aba3005443_cf722f27b0" tabindex="-1" value="">
            </div>
          </form>
        </div>

      </main>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    MicroModal.init();
  });
</script>