config/routes.rb
Rails.application.routes.draw do

  root   'basic_pages#home'
  get    '/about',                to: 'basic_pages#about'
  get    '/addin-support',        to: 'basic_pages#addin_support'
  get    '/privacy',              to: 'basic_pages#privacy'
  get    '/pricing',              to: 'basic_pages#pricing'
  get    '/purchase-complete',    to: 'basic_pages#purchase_complete'
  get    '/join-tips',            to: 'basic_pages#join_tips'
  get    '/libraries',            to: 'basic_pages#libraries'
  get    '/community-centers',    to: 'basic_pages#community_centers'
  get    '/training',             to: 'basic_pages#training'
  get    '/excel-training/:slug', to: 'basic_pages#cities', as: 'city', constraints: CityConstraint.new

  resources :tips, path: "spreadsheet-tips", param: :slug, only: [:index, :show]
  get '/tips', to: redirect('/spreadsheet-tips')
  get '/tips/:tip_name', to: redirect('/spreadsheet-tips/%{tip_name}')

  resources :charges, only: [:create]

  # Devise routes for the main website.
  devise_for :users,
    controllers: {
      passwords: 'users/passwords',
      confirmations: 'users/confirmations',
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }
  # Additional routes for custom actions
  devise_scope :user do
    put 'users/update_password', to: 'users/registrations#update_password'
    put 'users/update_info', to: 'users/registrations#update_info'
  end
  # Short url with redirect created for giveaway cards and other printed materials.
  get '/sign-up', to: redirect('/users/sign_up')

  # Redirects from version 1 of the product (since there are still some old links out there)
  get '/courses(/*all)', to: redirect(path: '/#courses')

  # Routes namespaced under /addin
  namespace :addin do
    root 'basic_pages#index', as: :root
    get  'purchase-complete', to: 'basic_pages#purchase_complete'

    resources :charges, only: [:create]

    # Creates
    #  /addin/courses
    resources :courses, only: [:index, :show] do

      # Creates
      #   /addin/courses/:id/conclusion
      get 'conclusion', on: :member

      # Creates
      #  /addin/courses/:id/lessons
      #  /addin/courses/:id/lessons/:number_in_course
      resources :lessons, param: :number_in_course, only: [:index, :show] do

        # Creates
        #   /addin/courses/:id/lessons/:number_in_course/challenge
        #   /addin/courses/:id/lessons/:number_in_course/full-screen-video
        get 'challenge', on: :member
        get 'fullscreen', on: :member
      end
    end

    post 'feedback/create', to: 'feedback#create'
    post 'feedback/create-challenge', to: 'feedback#createChallenge'
    post 'completions/create', to: 'completions#create'

    # Devise routes & controllers for the addin.
    #
    # The main website and addin have their own devise routes and controllers but they share the model.
    #
    # See the routes "devise_for" generates at:
    #   http://www.rubydoc.info/github/plataformatec/devise/master/ActionDispatch/Routing/Mapper%3Adevise_for
    devise_for :users, skip: [:passwords, :confirmations], skip_helpers: true,
      controllers: {
        registrations: 'addin/users/registrations',
        sessions: 'addin/users/sessions'
      },
      path_names: {
        sign_in: 'login',
        sign_out: 'logout'
      }
    # Additional routes for custom actions
    devise_scope :addin_user do
      put 'users/update_password', to: 'users/registrations#update_password'
      put 'users/update_info', to: 'users/registrations#update_info'
      get 'users/password/new', to: 'users/passwords#new'
      get 'users/confirmation/new', to: 'users/confirmations#new'
    end
    # Redirects for people using the addin's "up one level" button.
    get 'users', to: redirect('/addin/courses', status: 302)
    get 'users/password', to: redirect('/addin/users/login', status: 302)
    get 'users/confirmation', to: redirect('/addin/users/login', status: 302)
  end

  namespace :admin do
    root to: "courses#index"
    resources :courses
    resources :lessons
    resources :users
    resources :tips
    resources :course_completions
    resources :lesson_completions
    resources :challenge_completions
    resources :whitelisted_ips
  end
end
# (For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html)

app/controllers/addin/basic_pages_controller.rb
class Addin::BasicPagesController < ApplicationController
  include AddinSetup

  def index
    redirect_to addin_courses_path
  end

  def purchase_complete
  end
end

app/controllers/addin/charges_controller.rb
class Addin::ChargesController < ApplicationController

  # Create charges for transactions in the addin. It's similar to the controller on the main
  # website, but it has addin-specific redirects.
  def create
    stripeEmail = params[:stripeEmail]
    existing_user = User.find_by(email: stripeEmail)

    if existing_user && !existing_user.free?
      # The user was previously upgraded and shouldn't be charged to get upgraded again.
      flash[:error] = I18n.t("charges.existing_account_already_upgraded", email: stripeEmail)
      redirect_to addin_courses_path and return
    end

    customer = Stripe::Customer.create(
      email: stripeEmail,
      source: params[:stripeToken]
    )

    amount = 7900

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: amount,
      description: 'Gridmaster Premium',
      currency: 'usd'
    )

    attributes = { customer_id: customer.id, access_level: 'premium' }

    if existing_user
      existing_user.assign_attributes(attributes)
      existing_user.save
      flash[:success] = I18n.t("charges.existing_account_upgraded", email: stripeEmail)
    else
      new_user = User.create_temp_account(stripeEmail, attributes)
      new_user.send_confirmation_and_reset_instructions
      sign_in(:addin_user, new_user)
      flash[:success] = I18n.t("charges.account_created_and_upgraded", email: stripeEmail)
    end

    redirect_to addin_purchase_complete_path(:transaction_id => charge.id)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to addin_courses_path
  end
end

app/controllers/addin/completions_controller.rb
class Addin::CompletionsController < ApplicationController # DeviseController?
  # Prevent non-authenticated users from POSTing to the basic create endpoint.
  # This is what prompts users to create an account to not lose their progress.
  before_action :authenticate_addin_user!

  def create
    data_response = CompletionService.new.save_progress(challenge_completion_params)
    render :json => data_response
  end

  private
    def challenge_completion_params
      params.require(:completion).permit(:user_id, :course_id, :lesson_id, :challenge_step)
    end
end

app/controllers/addin/courses_controller.rb
class Addin::CoursesController < ApplicationController
  include AddinSetup

  # /addin/courses
  def index
    @user = addin_user_signed_in? ? current_addin_user : User.new
    @courses = Course.order(:id).all

    # Add a completion flag to each lesson
    completedCourses = CourseCompletion.where(user_id: @user.id).distinct.pluck(:course_id)
    @courses.each do |course|
      course.completed = completedCourses.include? course.id
    end
  end

  # /addin/course/:id
  def show
    # This action is not currently being used, so we just redirect to the list of
    # all courses. This works well for our "up a level" button helper.
    redirect_to action: :index
  end

  # /addin/courses/:id/conclusion
  def conclusion
    @user = addin_user_signed_in? ? current_addin_user : User.new
    @course = Course.find(params['id'])
  end

end

app/controllers/addin/feedback_controller.rb
class Addin::FeedbackController < ApplicationController
  # Prevent non-authenticated users from POSTing to feedback endpoints.
  before_action :authenticate_addin_user!

  # This action is designed to receive generic feedback. You can override the default redirect
  # (which points back at your last page) by adding a hidden field where name="redirect" and
  # value="/my/relative/path".
  def create
    @feedback = Feedback.new(params[:feedback])
    @feedback.request = request
    if @feedback.deliver
      flash[:success] = "You know what? You're awesome, that's what! Big thanks for the feedback!"
    else
      flash[:error] = "Well this is awkward. Something went wrong and we can't send your feedback right now. Try emailing us at info@gridmaster.io."
    end

    redirect_to params[:redirect] || stored_location_for(:addin_user) || addin_courses_path
  end

  # The challenge feedback form is AJAX submitted, so we have a separate action that handles things differently.
  def createChallenge
    @feedback = Feedback.new(params[:feedback])
    @feedback.request = request
    if @feedback.deliver
      flash.now[:success] = "You know what? You're awesome, that's what! Big thanks for the feedback!"
    else
      flash.now[:error] = "Well this is awkward. Something went wrong and we can't send your feedback right now. Try emailing us at info@gridmaster.io."
    end

    render :template => "addin/shared/_flash", :layout => false
  end


end

app/controllers/addin/lessons_controller.rb
class Addin::LessonsController < ApplicationController
  include AddinSetup

  # /addin/courses/:id/lessons
  def index
    @user = current_addin_user_or_temp_user
    @course = Course.find_by(id: params['course_id']) or not_found
    @lessons = Lesson.where(course_id: params['course_id']).order(:order_in_course)

    # Add a completion flag to each lesson
    completedLessons = LessonCompletion.where(user_id: @user.id, course_id: @course.id).distinct.pluck(:lesson_id)
    @lessons.each do |lesson|
      lesson.completed = completedLessons.include? lesson.id
    end
  end

  # /addin/courses/:id/lessons/:number_in_course
  def show
    @user = current_addin_user_or_temp_user
    @lesson = Lesson.where(course_id: params['course_id']).find_by(order_in_course: params['number_in_course']) or not_found
  end

  # /addin/courses/:id/lessons/:number_in_course/fullscreen
  def fullscreen
    @lesson = Lesson.where(course_id: params['course_id']).find_by(order_in_course: params['number_in_course']) or not_found
    render :layout => 'addin-fullscreen-video'
  end

  # /addin/courses/:id/lessons/:number_in_course/challenge
  def challenge
    @user = current_addin_user_or_temp_user
    @lesson = Lesson.where(course_id: params['course_id']).find_by(order_in_course: params['number_in_course']) or not_found
    @lessonTotal = Course.find(params['course_id']).lessons.size

    # Add a completion flag to each challenge step
    completedSteps = ChallengeCompletion.where(user_id: @user.id, lesson_id: @lesson.id).distinct.pluck(:challenge_step)
    @lesson.challenge_data['steps'].each_with_index do |step, index|
      step['completed'] = completedSteps.include? index + 1
    end

    # Ensure the minimum_password_length info is available to the sign-up form.
    set_minimum_password_length
  end

  private
    def current_addin_user_or_temp_user
      # By populating the request.remote_ip, we ensure that anonymous users can be IP whitelisted too.
      addin_user_signed_in? ? current_addin_user : User.new(current_sign_in_ip: request.remote_ip)
    end

    # Devise methods used for login/signup prompts on lesson pages.
    def resource_name
      :addin_user
    end
    helper_method :resource_name

    def resource
      @resource ||= User.new
    end
    helper_method :resource

    def devise_mapping
      @devise_mapping ||= Devise.mappings[:addin_user]
    end
    helper_method :devise_mapping

    def resource_class
      User
    end
    helper_method :resource_class

    def set_minimum_password_length
      if devise_mapping.validatable?
        @minimum_password_length = resource_class.password_length.min
      end
    end

end

app/controllers/addin/users/confirmations_controller.rb
# This is a custom "semi-devise" controller. It's just for setting up a form,
# that POSTs to devise-powered endpoints on the main website. It inherits from
# a parent devise controller so we can access some useful varibles in our form.
class Addin::Users::ConfirmationsController < DeviseController
  include AddinSetup

  def new
    self.resource = resource_class.new
  end

end

app/controllers/addin/users/passwords_controller.rb
# This is a custom "semi-devise" controller. It's just for setting up a form,
# that POSTs to devise-powered endpoints on the main website. It inherits from
# a parent devise controller so we can access some useful varibles in our form.
class Addin::Users::PasswordsController < DeviseController
  include AddinSetup

  def new
    self.resource = resource_class.new
  end

end

app/controllers/addin/users/registrations_controller.rb
# See original registration controller:
#   https://github.com/plataformatec/devise/blob/71fc5b351a8e8473733b0ca29d60c06e43a0efe1/app/controllers/devise/registrations_controller.rb
#
# Notes on overriding:
#   We've namespaced our resource, which changes `user` --> `addin_user` in tons of places (like
#   names for helpers, methods, variables, and more). Thus, any instructions you find online may
#   need to be adjusted accordingly. Here are some examples of changed values:
#    `authenticate_user` --> `authenticate_addin_user`
#    `current_user` --> `current_addin_user`
#
# Useful values from the parent controller:
#   `resource`      - Devise's abstract variable for our resource. In our case, we can access the
#                     same resource with `current_addin_user`, which is more expressive.
#   `resource_name` - Devise's variable for your resource name. Ours is `:addin_user` instead of
#                     `:user` because we are namespacing.
class Addin::Users::RegistrationsController < Devise::RegistrationsController
  include AddinSetup
  # Copy over `before_actions`, so I can add more actions without blowing away existing ones.
  prepend_before_action :require_no_authentication, only: [:new, :create, :cancel]
  prepend_before_action :authenticate_scope!, only: [:edit, :update, :destroy, :update_password, :update_info]
  prepend_before_action :set_minimum_password_length, only: [:new, :edit, :update_password]
  prepend_before_action :check_captcha, only: [:create]

  # Update the existing registrations#create to record completions, if any completion
  # data exists in the form. All the new stuff is inside a "if params[:completion]".
  def create
    if params[:completion]
      # Set the stored redirect location to a challenge url with the next challenge step
      set_redirect_to_next_challenge_step(params[:completion])
    end

    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?

    if resource.persisted?
      if resource.active_for_authentication?

        # If we made it here then sign up was successful, so we can record completions.
        if params[:completion]
          CompletionService.new.save_progress(
            user_id: resource.id,
            course_id: params[:completion][:course_id],
            lesson_id: params[:completion][:lesson_id],
            challenge_step: params[:completion][:challenge_step]
          )
        end

        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      # The sign up failed, so we set the completion data to a class variable allowing it
      # to be pre-populated on the next sign up form that gets rendered.
      if params[:completion]
        @completion_data = params[:completion]
      end

      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource, location: new_addin_user_registration_path
    end
  end

  # I wanted to be able to update basic account details separately
  # from password so instead of using the default `update` action,
  # I'm creating my own `update_password` and `update_info` actions,
  # and reusing whatever bits make sense.
  def update
    redirect_to current_addin_user
  end

  def update_password
    if current_addin_user.update_with_password(user_password_params)
      flash[:success] = I18n.t("devise.registrations.update_password")
      bypass_sign_in(current_addin_user)
      redirect_to action: :edit
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  def update_info
    if current_addin_user.update_without_password(user_basic_params)
      flash[:success] = I18n.t("devise.registrations.update_info")
      redirect_to action: :edit
    else
      respond_with resource
    end
  end

  private
    def user_password_params
      params.require(:addin_user).permit(:current_password, :password, :password_confirmation)
    end

    def user_basic_params
      params.require(:addin_user).permit(:name, :email)
    end

    def check_captcha
      if !verify_recaptcha
        # Recaptcha failed. In other words, this might be a bot.
        self.resource = resource_class.new sign_up_params
        # Look for any other validation errors besides Recaptcha
        resource.validate
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end

end

app/views/addin/shared/_devise-links.html.erb
<div class="ms-font-m">
<%- if controller_name != 'sessions' %>
  <div class="devise-form-link">Already have an account? <%= link_to "Log in", new_session_path(resource_name) %></div>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <div class="devise-form-link">Don't have an account? <%= link_to "Sign up for free", new_registration_path(resource_name) %></div>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%# point to to our custom password reset path %>
  <div class="devise-form-link"><%= link_to "Forgot your password?", addin_users_password_new_path %></div>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%# point to to our custom confirmations path %>
  <div class="devise-form-link"><%= link_to "Didn't receive confirmation instructions?", addin_users_confirmation_new_path %></div>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <div class="devise-form-link"><%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %></div>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <div class="devise-form-link"><%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %></div>
  <% end -%>
<% end -%>
</div>

app/views/addin/shared/_flash.html.erb
<%# I put this in its own file so it could be embedded in templates, as
    well as rendered and returned as data for forms submitting via AJAX %>

<div class="addin-flash-wrap">
  <% flash.each do |key, value| %>
    <div class="ms-MessageBar addin-flash <%= addin_flash_class(key) %>">
      <div class="ms-MessageBar-content">
        <div class="ms-MessageBar-icon">
          <i class="ms-Icon <%= addin_flash_icon(key) %>"></i>
        </div>
        <div class="ms-MessageBar-text">
          <%= value %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/addin/shared/_footer.html.erb
<footer class="ms-bgColor-neutralDark">

  <div class="ms-landing-page__footer">
    <%= link_to addin_root_path, class: "ms-landing-page__footer--left gridmaster-wordmark-wrapper clean-up-listeners" do %>
      <%= image_tag("gridmaster-addin-footer-logo.png") %>
    <% end %>
    <div>
      <a href="#" class="addin-settings ms-landing-page__footer--right">
        <i class="ms-Icon addin-settings__icon ms-Icon--Settings ms-fontColor-white"></i>
      </a>
      <nav class="addin-footer-nav">
        <% if addin_user_signed_in? %>
          <%# This fake logout link simply clicks the real (hidden) one. This allows us to add listeners
              that do things before logging out (like clean up Excel artifacts). This normally isn't possible
              because links with method: :delete have rails JS listeners on them that we can't get in front of. %>
          <%= link_to "Log Out", '#', class: "addin-footer-nav__link fake-logout-link" %>
          <%= link_to "Log Out", destroy_addin_user_session_path, method: :delete, class: "addin-footer-nav__link real-logout-link is-hidden" %>
          <%= link_to "Profile", edit_addin_user_registration_path, class: "addin-footer-nav__link clean-up-listeners" %>
        <% else %>
          <%= link_to "Log In", new_addin_user_session_path, class: "addin-footer-nav__link clean-up-listeners" %>
          <%= link_to "Sign Up", new_addin_user_registration_path, class: "addin-footer-nav__link clean-up-listeners" %>
        <% end %>
      </nav>
    </div>
  </div>

</footer>

app/views/addin/shared/_general_feedback.erb
<div class="modal is-hidden" id="feedback">
  <div class="modal__inner">

      <div class="modal__header">
        <h2>Leave Feedback</h2>
        <a href="#0" class="modal__dismiss">
          <i class="ms-Icon ms-Icon--Cancel ms-fontColor-white modal__icon"></i>
        </a>
      </div>
      <div class="modal__body">
        <%= form_tag(addin_feedback_create_path, method: "post") do %>

          <p class="mar-bt ms-font-m">Hey there! Please let us know how we're doing:</p>

          <%= label_tag(:feedback, "Feedback", :class => "visuallyhidden") %>
          <%= text_area(:feedback, :message, :class => "full-width", :rows => 8) %>

          <p class="mar-bt ms-font-m">Seriously, we read every submission and use your feedback to make Gridmaster better.</p>

          <% if local_assigns[:redirect] %>
            <%= hidden_field_tag :redirect, redirect %>
          <% end %>

          <%= hidden_field :feedback, :metadata, :value => "General feedback from #{request.url}" %>
          <%= hidden_field :feedback, :name, :value => @user.name %>
          <%= hidden_field :feedback, :email, :value => @user.email %>
          <%= hidden_field :feedback, :nickname %>

          <%= submit_tag "Submit" %>

        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/addin/shared/_get_notified.erb
<div class="modal is-hidden" id="get-notified">
  <div class="modal__inner">
    <div class="modal__header">
      <h2>Get Notified</h2>
      <a href="#0" class="modal__dismiss">
        <i class="ms-Icon ms-Icon--Cancel ms-fontColor-white modal__icon"></i>
      </a>
    </div>
    <div class="modal__body">
      <p class="mar-bt ms-font-m">Sign up to get notified when new courses arrive.</p>

      <!-- Begin MailChimp Signup Form -->
      <div id="mc_embed_signup" class="courses-inline-signup">
        <form action="//gridmaster.us11.list-manage.com/subscribe/post?u=c6aa5d99b8059f1aba3005443&amp;id=65ef90be52" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
          <div id="mc_embed_signup_scroll">
            <label for="mce-EMAIL" class="ms-font-xs block">Email Address:</label>
            <div class="mc-field-group courses-inline-signup__inputs">
              <div>
                <input type="email" value="" name="EMAIL" class="required email full-width" placeholder="you@domain.com" id="mce-EMAIL" />
              </div>
              <div>
                <input type="submit" value="Submit" name="subscribe" id="mc-embedded-subscribe" />
              </div>
            </div>
            <div id="mce-responses" class="clear">
              <div class="response mar-top-sm" id="mce-error-response" style="display:none"></div>
              <div class="response mar-top-sm" id="mce-success-response" style="display:none"></div>
            </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c6aa5d99b8059f1aba3005443_65ef90be52" tabindex="-1" value=""></div>
          </div>
        </form>
      </div>
      <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script>
      <script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
      <!--End mc_embed_signup-->
    </div>
  </div>
</div>

app/views/addin/shared/_header.html.erb
<header class="ms-navigation-back-button__header ms-bgColor-neutralDark">
  <div class="ms-navigation-back-button__header--left">
    <%# Include "up-a-level" button, for all page except the top-level one %>
    <% if last_segment_of_current_url != 'courses' %>
      <%= link_to url_a_level_above_current_url, class: "ms-navigation-back-button__back clean-up-listeners" do %>
        <i class="ms-Icon ms-Icon--ChevronLeft ms-fontColor-white"></i>
      <% end %>
    <% end %>
  </div>
  <h1 id="nav-title" class="nav-title ms-navigation-back-button__header--center ms-fontWeight-light ms-fontColor-white">
    <%= yield :title %>
  </h1>
  <div class="ms-navigation-back-button__header--right"></div>
</header>

app/views/addin/shared/_purchase_prompt.erb
<div class="modal" id="purchase-prompt">
  <div class="modal__inner">
    <div class="modal__header">
      <h2>Get Full Access</h2>
    </div>
    <div class="modal__body">
      <p class="mar-bt ms-font-m">This content requires a premium account.</p>
      <p class="mar-bt ms-font-m">A premium account costs $79, one time, and gives you full access to <em>all of our current and future courses</em>.</p>
      <p class="mar-bt-20 ms-font-m"><strong>This is an investment in yourself.</strong> If for some reason you aren't satisfied, we'll refund you 100%.</p>

      <%= button_tag type: "submit", class: "ms-Button ms-Button--primary full-width mar-bt stripe-checkout--premium" do %>
        <span class="ms-Button-label msfix-button-lite">
          <%= addin_user_signed_in? ? 'Upgrade my Account' : 'Get a Premium Account' %>
        </span>
      <% end %>
      <% if !addin_user_signed_in? %>
        <p class="ms-font-m center">
          <%= link_to "I already have an account", new_session_path(resource_name) %>
        </p>
      <% end %>
    </div>
  </div>
</div>

<%#
  Adds Stripe Checkout (custom) to a page.

  It works by turning any button with a class of .stripe-checkout--premium
  into a premium stripe checkout button.

  This assumes it's only being embedded on a page once, and it's being embedded on
  a page that could have access to current_user (though it's protected in a condition)
%>
<script src="https://checkout.stripe.com/checkout.js"></script>
<script>
  // Global Stripe initialization
  var stripeHandler = StripeCheckout.configure({
    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
    name: 'Gridmaster',
    image: '<%= image_path('gridmaster-128.png') %>',
    email: '<%= current_addin_user.email if addin_user_signed_in? %>',
    zipCode: true,
    locale: 'auto',
    allowRememberMe: false,
    token: function(token) {
      GM.hardPost('<%= addin_charges_path %>', {
        authenticity_token: '<%= form_authenticity_token %>',
        stripeEmail: token.email,
        stripeToken: token.id
      });
    }
  });

  // "Premium" Button Setup
  (function() {
    function stripePremiumButtonCallback(e) {
      stripeHandler.open({
        description: 'Premium',
        amount: 7900,
        panelLabel: '<%= addin_user_signed_in? ? 'Upgrade Account' : 'Create Account' %>'
      });
      e.preventDefault();
    }

    var stripeButtons = document.querySelectorAll('.stripe-checkout--premium');

    for (i = 0; i < stripeButtons.length; i++) {
      stripeButtons[i].addEventListener('click', stripePremiumButtonCallback);
    }

    // Close Checkout on page navigation:
    window.addEventListener('popstate', function() {
      stripeHandler.close();
    });
  })();
</script>